name: CI Microservices Test

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and start services
        run: docker compose up -d --build

      - name: Wait for services
        run: |
          echo "Waiting for services..."
          sleep 60

      - name: Test Order Service
        run: curl --fail http://localhost:8081/api/order/allproducts

      - name: Test Product Service
        run: curl --fail http://localhost:8082/api/product/all

      - name: Test Inventory Service
        run: curl --fail http://localhost:8083/actuator/health

      - name: Test Eureka
        run: curl --fail http://localhost:8091/eureka/apps

      - name: Test API Gateway
        run: curl --fail http://localhost:8090/actuator/health

      - name: Stop services
        run: docker compose down
